language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository --yes ppa:ktm5j/uva-cs-ppa
  - sudo apt-get update
install: sudo apt-get install libboost-dev liblbfgs-dev swig flex python-nose
script:
  - make
  - make reranker
  - make -C second-stage/programs/features parallel-tools
  - make sparseval
  - sudo python setup.py install
  - nosetests --with-doctest -dv python/tests/
